export const statementList = [{
    id: 1,
    url1: 'public/img/sivak_1.jpg',
    name: 'Sivak',
    quote: `I do believe a coder has no social life.`,
    url2: 'public/img/sivak_2.jpg',
    url3: 'public/img/sivak_3.jpg',
}, {
    id: 2,
    url1: 'public/img/luben_1.jpg',
    name: 'Zan',
    quote: `If React makes it easier, I am really looking forward to it.`,
    url2: 'public/img/luben_2.jpg',
    url3: 'public/img/luben_3.jpg',
}, {
    id: 4,
    url1: 'public/img/malaiz_1.jpg',
    name: 'Malaiz',
    quote: `Yesterday I was in the unfamiliar territory – today it's familiar (:`,
    url2: 'public/img/malaiz_2.jpg',
    url3: 'public/img/malaiz_3.jpg',
}, {
    id: 5,
    url1: 'public/img/luben_1.jpg',
    name: 'David',
    quote: `Don't be impressed. This is all copy and paste.`,
    url2: 'public/img/luben_2.jpg',
    url3: 'public/img/luben_3.jpg',
}, {
    id: 6,
    url1: 'public/img/luben_1.jpg',
    name: 'Fi',
    quote: `I uploaded five pictues and Chris held my hand through it.`,
    url2: 'public/img/luben_2.jpg',
    url3: 'public/img/luben_3.jpg',
}, {
    id: 7,
    url1: 'public/img/luben_1.jpg',
    name: 'Bruno',
    quote: `I sometimes even dream of code.`,
    url2: 'public/img/luben_2.jpg',
    url3: 'public/img/luben_3.jpg',
}, {
    id: 8,
    url1: 'public/img/luben_1.jpg',
    name: 'Jens',
    quote: `There are some bugs to fix still – we were trying to keep ourselves busy.`,
    url2: 'public/img/luben_2.jpg',
    url3: 'public/img/luben_3.jpg',
}, {
    id: 9,
    url1: 'public/img/luben_1.jpg',
    name: 'Arthi',
    quote: `No. I don't want to do any kind of push.`,
    url2: 'public/img/luben_2.jpg',
    url3: 'public/img/luben_3.jpg',
}, {
    id: 10,
    url1: 'public/img/marina_1.jpg',
    name: 'Marina',
    quote: `I will pray to the god of github that there are no conflicts.`,
    url2: 'public/img/marina_2.jpg',
    url3: 'public/img/marina_3.jpg',
}, {
    id: 11,
    url1: 'public/img/luben_1.jpg',
    name: 'Samin',
    quote: `I'm sooo glad its weekend finally.`,
    url2: 'public/img/luben_2.jpg',
    url3: 'public/img/luben_3.jpg',
}, {
    id: 12,
    url1: 'public/img/fabian_1.jpg',
    name: 'Fabian',
    quote: `I do git branch now – to see where the hell I am.`,
    url2: 'public/img/fabian_2.jpg',
    url3: 'public/img/fabian_3.jpg',
}, {
    id: 13,
    url1: 'public/img/luben_1.jpg',
    name: 'Fi',
    quote: `Es ruckelt immer ein bisschen – bis das Leben in den nächsten Gang schaltet.`,
    url2: 'public/img/luben_2.jpg',
    url3: 'public/img/luben_3.jpg',
}, {
    id: 14,
    url1: 'public/img/chris_1.jpg',
    name: 'Chris',
    quote: `One more thing. I promise. Only one more thing.`,
    url2: 'public/img/chris_2.jpg',
    url3: 'public/img/chris_3.jpg',
}, {
    id: 15,
    url1: 'public/img/sivak_1.jpg',
    name: 'Sivak',
    quote: `I do nothing. Except this course and cook one meal a day.`,
    url2: 'public/img/sivak_2.jpg',
    url3: 'public/img/sivak_3.jpg',
}, {
    id: 17,
    url1: 'public/img/luben_1.jpg',
    name: 'Luben',
    quote: `Life is a list.`,
    url2: 'public/img/luben_2.jpg',
    url3: 'public/img/luben_3.jpg',
}, {
    id: 18,
    url1: 'public/img/luben_1.jpg',
    name: 'Luben',
    quote: `"Where you resolve this problem?!" I don't even want to get the problem!`,
    url2: 'public/img/luben_2.jpg',
    url3: 'public/img/luben_3.jpg',
}, {
    id: 19,
    url1: 'public/img/victor_1.jpg',
    name: 'Sima',
    quote: `I'm really shutting down now.`,
    url2: 'public/img/victor_2.jpg',
    url3: 'public/img/victor_3.jpg',
}, {
    id: 20,
    url1: 'public/img/victor_1.jpg',
    name: 'Victor',
    quote: `I'm super lost in the world.`,
    url2: 'public/img/victor_2.jpg',
    url3: 'public/img/victor_3.jpg',
}, {
    id: 21,
    url1: 'public/img/fabian_1.jpg',
    name: 'Fabian',
    quote: `I'm sure Chris also does "git add . ".`,
    url2: 'public/img/fabian_2.jpg',
    url3: 'public/img/fabian_3.jpg',
}, {
    id: 23,
    url1: 'public/img/victor_1.jpg',
    name: 'Victor',
    quote: `I think I need two lives to understand that.`,
    url2: 'public/img/victor_2.jpg',
    url3: 'public/img/victor_3.jpg',
}, {
    id: 24,
    url1: 'public/img/victor_1.jpg',
    name: 'Victor',
    quote: `I think, I fucked it up – like really good (using git).`,
    url2: 'public/img/victor_2.jpg',
    url3: 'public/img/victor_3.jpg',
}, {
    id: 25,
    url1: 'public/img/marina_1.jpg',
    name: 'Marina',
    quote: `I felt like we are all winners (:`,
    url2: 'public/img/marina_2.jpg',
    url3: 'public/img/marina_3.jpg',
}, {
    id: 26,
    url1: 'public/img/chris_1.jpg',
    name: 'Chris',
    quote: `The whole course is a lie. Until the last day`,
    url2: 'public/img/chris_2.jpg',
    url3: 'public/img/chris_3.jpg',
}, {
    id: 27,
    url1: 'public/img/malaiz_1.jpg',
    name: 'Malaiz',
    quote: `I'm even more confused now – … but thats OK.`,
    url2: 'public/img/malaiz_2.jpg',
    url3: 'public/img/malaiz_3.jpg',
}, {
    id: 28,
    url1: 'public/img/victor_1.jpg',
    name: 'Chris',
    quote: `I could talk some more about it – because I dont have any self-control`,
    url2: 'public/img/victor_2.jpg',
    url3: 'public/img/victor_3.jpg',
}, {
    id: 29,
    url1: 'public/img/victor_1.jpg',
    name: 'Jens',
    quote: `There is no content because Im boring.`,
    url2: 'public/img/victor_2.jpg',
    url3: 'public/img/victor_3.jpg',
}, {
    id: 30,
    url1: 'public/img/luben_1.jpg',
    name: 'Luben',
    quote: `"No man is free who is not master of himself" – Epictetus`,
    url2: 'public/img/luben_2.jpg',
    url3: 'public/img/luben_3.jpg',
}];
